name: Azure Login Test

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  test-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Show Azure Subscription Info
        run: |
          az account show
