name: Infra + App Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Check Tools
        run: |
          terraform -version
          kubectl version --client
          docker version

      - name: Terraform Apply
        working-directory: infra
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group sujeetrg1 --name autodsujeetgit --overwrite-existing

      - name: Build Docker Image and Push to ACR
        run: |
          az acr login --name autosujeetgit
          docker build -t autosujeetgit.azurecr.io/myapp:v1 .
          docker push autosujeetgit.azurecr.io/myapp:v1

      - name: Deploy App to AKS
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
